import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import ReduxProvider from "@/redux/provider";
export const metadata: Metadata = {
  title: "Comico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className="">
          <Navbar />
          <main className=" p-2  ">{children}</main>
          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
